### ISSUE TITLE
Very poor contrast for selection in command palette

### ISSUE THREAD

**Issue by falaeco** [Swiiip/sunset-theme-vscode#3]
This has been driving me crazy! It's nearly impossible to see the selected item in menu like command palette. I also have been trying many different selector for customizing this color to say yellow but I couldn't find the right configuration. I think the theme could benefit from a more contrasting color adjustement. In the picture view toggle word wrap is the option selected.

![image](https://user-images.githubusercontent.com/32775723/79905537-68aa6100-83e4-11ea-929b-8bf1ad8bfb2b.png)

**Comment by Swiiip** [comment]
Hello, do you have the last version of the color theme ? This is what's rendered on my end.
![image](https://user-images.githubusercontent.com/7131654/79985773-65c67380-84ab-11ea-8e76-22cca2f4b569.png)
There should be a slight difference in the backgrounds, the focused background being grey-ish.

However, I do understand that the contrast is not very noticeable. What would you think if we change the foreground of the focused elements to get more contrast like this ?

![image](https://user-images.githubusercontent.com/7131654/79986779-e20d8680-84ac-11ea-9db6-f717a13f95b3.png)

**Comment by falaeco** [comment]
Hi Swiip, thanks for replying so quickly! I am currently using version 0.9.2 on my windows and it's rendering like the picture I have posted above. However, on my mac, the window appear black and the contrast is much more apparent, which leads me to think that the command palette on window for dark themes are not as customizable as the one for mac. Macs also benefits from increased contrast thanks to the retina screens.

<img width="622" alt="Screen Shot 2020-04-23 at 21 09 41" src="https://user-images.githubusercontent.com/32775723/80164537-414fc180-85a7-11ea-8b39-8b265abe5a9c.png">

I think also that changing the foreground color of the selected item is a good idea and fits well with the rest of the theme. Thank you for making this theme, its the perfect blend between monokai and dark+ and most importantly, it's very functional and non distracting

**Comment by JasonTypesCodes** [comment]
Hi!  I really like this theme, but I'm experiencing the same issue @falaeco described above:

![image](https://user-images.githubusercontent.com/1888131/99488037-24a51d80-292d-11eb-8640-9fdbbef56902.png)

I spent some time digging through [this reference](https://code.visualstudio.com/api/references/theme-color) but haven't had much luck identifying which setting controls the background color of the command palette

**Comment by xarantolus** [comment]
I've had this same issue (on Windows)
![image](https://user-images.githubusercontent.com/32465636/99496702-17138600-2975-11eb-8890-0d72a432489b.png)


Then added this to my `settings.json`:

```json
    // ...    
    "workbench.colorCustomizations": {
        "[Sunset Theme]": {
            "list.focusBackground": "#b14a0680"
        }
    },
    // ...
```

And now it looks like this:
![fixed](https://user-images.githubusercontent.com/32465636/99496883-5b068b00-2975-11eb-81a3-417c5c11b4e8.png)

**Comment by Swiiip** [comment]
Hello Thanks for your inputs,

I've published a new version that uses the new quickInput.background setting.
This is the result
![image](https://user-images.githubusercontent.com/7131654/99520878-f73f8a80-2993-11eb-8c9a-fc31c85b1cf3.png)
I think it's more aligned with the overall look and feel of the theme.
What do you think ?

**Comment by JasonTypesCodes** [comment]
@Swiiip Looks great on Linux:

![image](https://user-images.githubusercontent.com/1888131/99548811-a5d8d080-297e-11eb-9dcd-181ac72b6380.png)

Thanks!
